### ISSUE TITLE
Is there any debug info being logged anywhere

### ISSUE THREAD

**Issue by PsySc0rpi0n** [daywalker90/sling#4]
Is there any way of getting any output whatsoever from the plugin? I tried to run it but the only thing I could see was the prompt locked. I had to terminate te plugin with ctrl+c after a couple of hours of absolute inactivity.

The command I ued was:
```
$ ./sling -k scid=827557x1201x1 direction=pull amount=1000000 maxppm=800 maxhops=5 candidates'["837250x1044x1", "840918x2479x0"]' paralleljobs=4
^C
$
```

**Comment by daywalker90** [comment]
thats not how you run cln plugins. You need to put a sym link to sling in your plugins folder or put 
```
plugin=/path/to/sling
```
in you cln config or run
```
lightning-cli plugin start /path/to/sling
```
then you get plenty logging if your general logging is set to debug :)

**Comment by PsySc0rpi0n** [comment]
> thats not how you run cln plugins. You need to put a sym link to sling in your plugins folder or put
> 
> ```
> plugin=/path/to/sling
> ```
> 
> in you cln config or run
> 
> ```
> lightning-cli plugin start /path/to/sling
> ```
> 
> then you get plenty logging if your general logging is set to debug :)

Yes, I know, but look what I get after starting the plugin:
```
...
{
         "name": "/home/psysc0rpi0n/Downloads/plugins/sling/sling",
         "active": true,
         "dynamic": true
      }
   ]
}
```
When I try to use it:
```
$ lightning-cli sling
{
   "code": -32601,
   "message": "Unknown command 'sling'"
}
```

**Comment by PsySc0rpi0n** [comment]
Ok, may I ask a couple more questions in this thread or I should open other issues?
 I'll ask here. If you see fit, I'll open new issue with quiestions.

1 - How can we tell a job has finished, either with success or not? The only output from the plugin in the terminal is this:
```
$ lightning-cli sling-go
{
   "jobs_started": 4
}
```

In the debug file I see:
```
2024-05-07T22:18:19.635Z INFO    plugin-sling: 827557x1201x1/1: No candidates found. Adjust out_ppm or wait for liquidity. Sleeping...
2024-05-07T22:18:19.636Z INFO    plugin-sling: 827557x1201x1/1: could not find a route. Sleeping...
2024-05-07T22:18:19.658Z INFO    plugin-sling: 827557x1201x1/2: No candidates found. Adjust out_ppm or wait for liquidity. Sleeping...
2024-05-07T22:18:19.658Z INFO    plugin-sling: 827557x1201x1/2: could not find a route. Sleeping...
2024-05-07T22:18:19.678Z INFO    plugin-sling: 827557x1201x1/3: No candidates found. Adjust out_ppm or wait for liquidity. Sleeping...
2024-05-07T22:18:19.679Z INFO    plugin-sling: 827557x1201x1/3: could not find a route. Sleeping...
2024-05-07T22:18:19.700Z INFO    plugin-sling: 827557x1201x1/4: No candidates found. Adjust out_ppm or wait for liquidity. Sleeping...
2024-05-07T22:18:19.701Z INFO    plugin-sling: 827557x1201x1/4: could not find a route. Sleeping...
```

The sleeping word is the keyword to say it failed?

**Comment by daywalker90** [comment]
1. sling-stats without any further argument, then you will see an overview over all jobs
2. it failed to find any route that fits your settings, but it will try until you stop it to find a route with liquidity that fits your settings

**Comment by daywalker90** [comment]
if you set logging to debug level the routes will be printed to log. After the fact sling only saves your "from" and "to" local channels for the statistics: use sling-stats <scid> to see the list of the top_5_channel_partners.

**Comment by daywalker90** [comment]
this is how you can set the log level of sling to debug: `log-level=debug:plugin-sling`. And i meant sling-stats WITH the scid of a job, e.g. `sling-stats 735144x2710x1`

**Comment by daywalker90** [comment]
setting the log-level for subsystems/plugins is documented here btw: https://docs.corelightning.org/reference/lightningd-config
